use jcase4db;
CREATE TABLE BOOK (
ISBN char(13) not null,
COPY int not null,
GENRE varchar(45),
PDATE date,
PUBLISHER varchar(45),
SIZE int,
PRIMARY KEY (ISBN,COPY)
);
CREATE TABLE AUTHOR (
isbn char(13) not null,
copy int not null,
AF varchar(45),
AM varchar(45),
AL varchar(45),
PRIMARY KEY (isbn,copy,AF,AM,AL),
FOREIGN KEY (isbn,copy) REFERENCES BOOK (ISBN,COPY)
);
CREATE TABLE FLOOR (
F_NUM int not null,
F_RULE bit,
PRIMARY KEY (F_NUM)
);
CREATE TABLE DEPART (
D_NUM int not null,
D_NAME varchar(45),
D_Head char(7),
PRIMARY KEY (D_NUM)
);
CREATE TABLE REF_BOOK (
REF_ISBN char(13) not null,
REF_COPY int not null,
PRIMARY KEY (REF_ISBN,REF_COPY),
FOREIGN KEY (REF_ISBN,REF_COPY) REFERENCES BOOK (ISBN,COPY)
);
CREATE TABLE TU_AFFILIATE (
TUID char(7) not null,
AFPhone char(10),
AFF varchar(45),
AFM varchar(45),
AFL varchar(45),
PRIMARY KEY (TUID)
);
CREATE TABLE NON_STAFF (
NS_TUID char(7) not null,
NS_TYPE varchar(45),
PRIMARY KEY (NS_TUID),
FOREIGN KEY (NS_TUID) REFERENCES TU_AFFILIATE (TUID)
);
CREATE TABLE LIB_STAFF (
LS_TUID char(7) not null,
LS_FLOOR int,
LS_DEPART int,
PRIMARY KEY (LS_TUID),
FOREIGN KEY (LS_TUID) REFERENCES TU_AFFILIATE (TUID),
FOREIGN KEY (LS_FLOOR) REFERENCES FLOOR (F_NUM),
FOREIGN KEY (LS_DEPART) REFERENCES DEPART (D_NUM)
);
CREATE TABLE AS_LIBRARIAN (
AS_TUID char(7) not null,
AS_DEPART int not null,
PRIMARY KEY (AS_TUID),
FOREIGN KEY (AS_TUID) REFERENCES LIB_STAFF (LS_TUID),
FOREIGN KEY (AS_DEPART) REFERENCES DEPART (D_NUM)
);
CREATE TABLE LIBRARIAN (
L_TUID char(7) not null,
L_DEGREE varchar(45),
PRIMARY KEY (L_TUID),
FOREIGN KEY (L_TUID) REFERENCES LIB_STAFF (LS_TUID)
);
CREATE TABLE STUDENT_WORKER (
SW_TUID char(7) not null,
PRIMARY KEY (SW_TUID),
FOREIGN KEY (SW_TUID) REFERENCES LIB_STAFF (LS_TUID)
);
CREATE TABLE REQUEST_FORM (
RF_NUM int not null,
RF_TOPIC varchar(45),
RF_DATE date,
RFNS_TUID char(7),
RFL_TUID char(7),
PRIMARY KEY (RF_NUM),
FOREIGN KEY (RFNS_TUID) REFERENCES NON_STAFF (NS_TUID),
FOREIGN KEY (RFL_TUID) REFERENCES LIBRARIAN (L_TUID)
);
CREATE TABLE NREF_BOOK (
NREF_ISBN char(13) not null,
NREF_COPY int not null,
CI_TUID char(7),
CI_DATE date,
CO_TUID char(7),
CO_DATE date,
RENEW_TUID char(7),
ACQUIRE_TUID char(7),
V_NAME varchar(45),
V_TYPE varchar(45),
V_PHONE char(10),
S_TUID char(7),
PRIMARY KEY (NREF_ISBN,NREF_COPY),
FOREIGN KEY (NREF_ISBN,NREF_COPY) REFERENCES BOOK (ISBN,COPY),
FOREIGN KEY (CI_TUID) REFERENCES TU_AFFILIATE (TUID),
FOREIGN KEY (CO_TUID) REFERENCES TU_AFFILIATE (TUID),
FOREIGN KEY (RENEW_TUID) REFERENCES TU_AFFILIATE (TUID),
FOREIGN KEY (ACQUIRE_TUID) REFERENCES TU_AFFILIATE (TUID),
FOREIGN KEY (S_TUID) REFERENCES STUDENT_WORKER (SW_TUID)
);
CREATE TABLE REQUEST (
TUA_TUID char(7) not null,
NREF_isbn char(13) not null,
NREF_copy int not null,
PRIMARY KEY (TUA_TUID,NREF_isbn,NREF_copy),
FOREIGN KEY (TUA_TUID) REFERENCES TU_AFFILIATE (TUID),
FOREIGN KEY (NREF_isbn,NREF_copy) REFERENCES NREF_BOOK (NREF_ISBN,NREF_COPY)
);
CREATE TABLE NON_BOOK_RESOURCE (
R_NUM int not null,
R_TYPE varchar(45),
R_DATE date,
R_TIME time,
R_TUID char(7),
R_FLOOR int,
PRIMARY KEY (R_NUM),
FOREIGN KEY (R_TUID) REFERENCES TU_AFFILIATE (TUID),
FOREIGN KEY (R_FLOOR) REFERENCES FLOOR(F_NUM)
);




